spring:
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:sqlite:./db/app.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 20
      connection-init-sql: "PRAGMA foreign_keys=ON"
server:
  port: 8085

fshs:
  #mac
  base-path: /Users/user/Desktop/programming/fshs
  #server
#  base-path: /home/user/hosting/fshs2

  storage:
    data-dir-name: data # 시스템 루트의 폴더명
    temp-dir-name: temp # 임시 폴더의 폴더명
    thumbnail-dir-name: thumbnail # 썸네일 폴더의 폴더명
    data-path: ${fshs.base-path}/${fshs.storage.data-dir-name} #절대 경로
    temp-path: ${fshs.base-path}/${fshs.storage.temp-dir-name} #절대 경로
    thumbnail-path: ${fshs.base-path}/${fshs.storage.thumbnail-dir-name} #절대 경로

ffmpeg:
  #mac
  ffmpeg: /opt/homebrew/bin/ffmpeg
  ffprobe: /opt/homebrew/bin/ffprobe
  #server
#  ffmpeg: /usr/bin/ffmpeg
#  ffprobe: /usr/bin/ffprobe
